"""Kafka topic + event-type constants. Kafka is an application event bus only:
PostgreSQL = current state, Redis = fast/temporary state, Kafka = what happened.
"""

TOPIC_AMENITY_EVENTS = "amenity-events"
TOPIC_WAITLIST_EVENTS = "waitlist-events"
TOPIC_BUGGY_EVENTS = "buggy-events"
TOPIC_FOLIO_EVENTS = "folio-events"
TOPIC_MAINTENANCE_EVENTS = "maintenance-events"
TOPIC_RECOMMENDATION_EVENTS = "recommendation-events"
TOPIC_EMERGENCY_EVENTS = "emergency-events"

EVENT_WAITLIST_JOINED = "waitlist.joined"
EVENT_AMENITY_AVAILABLE = "amenity.available"
EVENT_AMENITY_STATUS_CHANGED = "amenity.status_changed"
EVENT_BUGGY_REQUESTED = "buggy.requested"
EVENT_BUGGY_ASSIGNED = "buggy.assigned"
EVENT_FOLIO_CHARGE_ADDED = "folio.charge_added"
EVENT_CHECKOUT_COMPLETED = "checkout.completed"
EVENT_AMENITY_OFFER_CREATED = "amenity.offer_created"
EVENT_AMENITY_OFFER_EXPIRED = "amenity.offer_expired"
EVENT_AMENITY_RESERVED = "amenity.reserved"
EVENT_MAINTENANCE_RISK_DETECTED = "maintenance.risk_detected"
EVENT_MAINTENANCE_TASK_CREATED = "maintenance.task_created"
EVENT_AMENITY_ALTERNATIVE_RECOMMENDED = "amenity.alternative_recommended"
EVENT_NOTIFICATION_SENT = "notification.sent"
EVENT_NOTIFICATION_ACKNOWLEDGED = "notification.acknowledged"
EVENT_NOTIFICATION_ESCALATED = "notification.escalated"
EVENT_VOICE_CALL_INITIATED = "voice_call.initiated"
EVENT_VOICE_CALL_COMPLETED = "voice_call.completed"
EVENT_SOS_CREATED = "sos.created"
EVENT_EMERGENCY_BROADCAST = "emergency.broadcast"
